/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    'aws_project_region': 'eu-west-1',
    'aws_cognito_identity_pool_id': 'eu-west-1:31afe668-84e5-4e64-a005-614fa6a48528',
    'aws_cognito_region': 'eu-west-1',
    'aws_user_pools_id': 'eu-west-1_dXBs9qNxJ',
    'aws_user_pools_web_client_id': '16u6m12nuvn7ncouulpcpf154b',
    'oauth': {},
    'aws_cloud_logic_custom': [
        {
            'name': 'myapi',
            'endpoint': 'https://kzpefsubke.execute-api.eu-west-1.amazonaws.com/dev',
            'region': 'eu-west-1'
        }
    ],
    'aws_appsync_graphqlEndpoint': 'https://rh3zugtdxnb2lpwsq4arwbmwlq.appsync-api.eu-west-1.amazonaws.com/graphql',
    'aws_appsync_region': 'eu-west-1',
    'aws_appsync_authenticationType': 'API_KEY',
    'aws_appsync_apiKey': 'da2-dxam5cowffgdzdrnhxggrewasq',
    'aws_user_files_s3_bucket': 'riddlesapi7df1457fc0fc4d009ac10b7d1b923ad2211857-dev',
    'aws_user_files_s3_bucket_region': 'eu-west-1',
    'public_url_prefix': 'https://s3-eu-west-1.amazonaws.com/riddlesapi7df1457fc0fc4d009ac10b7d1b923ad2211857-dev/public/'
};


export default awsmobile;
